server:
  port: 8080
  host: "localhost"

api:
  Register: "/register"
  Login: "/login"
  Me: "/me"
  Files_Upload: "/files/upload"
  FileList: "/files/list"
  RemmainingStorage: "/storage/remaining"


jwt:
  secret: "qZqtnO9kFnhD2LJKsbtZLwRuFZzVv4UwNILfRYXaLa8="
  expiration_hours: 24

storage:
  path: "./storage"
  max_per_user: 104857600  # 100MB in bytes
  display_in_mb: true     # Set to true to display storage values in MB instead of bytes

# MongoDB Configuration
mongodb:
  uri: "mongodb+srv://EasyFresh:uYM27iKwl784AcXE@cluster0.oltgf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  database: "File_Storage"
  collections:
    users: "Go_users"
    files: "Go_files"
